In [1]:
import numpy as np

In [20]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
  
])

A, B

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]]))

# Zadanie 1

In [8]:
def validate_shapes(A, B):
    if A.shape[1] != B.shape[0]:
        raise Exception(f'cannot multiply matrices with shapes {A.shape} and {B.shape}')

        
def multiply_matrix_by_vector(M, V):
    """
    Mnozenie macierzy przez wektor
    """
    validate_shapes(M, V)
    M_height, M_width = M.shape
    result = np.zeros(M_height)
    
    for row in range(M_height):
        for col in range(M_width):
            result[row] += M[row, col] * V[col]
            
    return result


def mul1(A, B):
    """
    Mnozenie macierzy jako zlozenie mnozenia macierzy przez wiele wektorow.
    """
    validate_shapes(A, B)
    
    A_height, A_width = A.shape
    B_height, B_width = B.shape
    
    C = np.zeros((A.shape[0], B.shape[1]))
        
    for col in range(B_width):
        C[:, col] = multiply_matrix_by_vector(A, B[:, col])
        
    return C
        
    
print(mul1(A,B))

[[ -30.  -36.  -42.]
 [ -66.  -81.  -96.]
 [-102. -126. -150.]]


# Zadanie 2

In [4]:

def dot_product(A,B):
    if A.shape[0] != B.shape[0]:
        raise Exception(f'cannot make dot produtcts from matrices with shapes {A.shape} and {B.shape}')
    result = 0
    for i in range(A.shape[0]):
        result +=  A[i] *B[i]
    return result

def mul2(A, B):
    """
    Mnożenie macierzy jako złożenie mnożenia wierszy przez kolumny
    """
    validate_shapes(A,B)
    C = np.zeros((A.shape[0],B.shape[1]))
    for a_row in range(A.shape[0]):
        for b_col in range(B.shape[1]):
            C[a_row][b_col] = dot_product(A[a_row,:], B[:,b_col])
    return C
print(mul2(A,B))
        

[[ -30.  -36.  -42.]
 [ -66.  -81.  -96.]
 [-102. -126. -150.]]


# Zadanie 3

In [72]:
def add_matrices(A,B):
    if A.shape != B.shape:
        raise Exception(f'cannot add matrices with shapes {A.shape} and {B.shape}')
    result = np.zeros((A.shape[0],B.shape[1]))
    for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            result[i][j] = A[i][j] + B[i][j]
    return result

def mul_rank_1_update(row, column):
    result = np.zeros((column.shape[0], row.shape[0]))
    for i in range(column.shape[0]):
        for j in range(row.shape[0]):
            result[i][j] = column[i] * row[j]
    return result
    

def mul3(A,B):
    """
    Mnożenie macierzy jako suma wielu rank-1 update 
    """
    validate_shapes(A,B)
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(A.shape[1]):
            rank_1_update =  mul_rank_1_update(A[:,i], B[i])
            C = add_matrices(C, rank_1_update)
    return C

print(mul3(A,B))
        

[[ -30.  -66. -102.]
 [ -36.  -81. -126.]
 [ -42.  -96. -150.]]


# Zadanie 4

In [18]:
def mul4(A, B):
    """
    Blokowe mnożenie macierzy 3x3
    Poszczególne bloki mnożone algorytmem klasycznym (funkcja mul2)
    """
    
    if A.shape != (3, 3) or B.shape != (3, 3):
        raise Exception('both matrices must have 3x3 size')
        
    C = np.zeros((3, 3))
    
    # lewy górny blok
    C[0:1, 0:1] = mul2(A[0:1, 0:1], B[0:1, 0:1]) + mul2(A[0:1, 1:3], B[1:3, 0:1])
    
    # lewy dolny blok
    C[1:3, 0:1] = mul2(A[1:3, 0:1], B[0:1, 0:1]) + mul2(A[1:3, 1:3], B[1:3, 0:1])
    
    # prawy górny blok
    C[0:1, 1:3] = mul2(A[0:1, 0:1], B[0:1, 1:3]) + mul2(A[0:1, 1:3], B[1:3, 1:3])
    
    # prawy dolny blok
    C[1:3, 1:3] = mul2(A[1:3, 0:1], B[0:1, 1:3]) + mul2(A[1:3, 1:3], B[1:3, 1:3])
    
    return C

mul4(A, B)

array([[ -30.,  -36.,  -42.],
       [ -66.,  -81.,  -96.],
       [-102., -126., -150.]])