In [2]:
import numpy as np

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
B = np.array([
    [-1, -2, -3],
    [-4, -5, -6],
  
])
B. shape


(2, 3)

In [24]:
def validate_shapes(A, B):
    if A.shape[1] != B.shape[0]:
        raise Exception(f'cannot multiply matrices with shapes {A.shape} and {B.shape}')

        
def multiply_matrix_by_vector(M, V):
    """
    Mnozenie macierzy przez wektor
    """
    validate_shapes(M, V)
    M_height, M_width = M.shape
    result = np.zeros(M_height)
    
    for row in range(M_height):
        for col in range(M_width):
            result[row] += M[row, col] * V[col]
            
    return result


def mul1(A, B):
    """
    Mnozenie macierzy jako zlozenie mnozenia macierzy przez wiele wektorow.
    """
    validate_shapes(A, B)
    
    A_height, A_width = A.shape
    B_height, B_width = B.shape
    
    result_columns = []
        
    for col in range(B_width):
        result_columns.append(multiply_matrix_by_vector(A, B[:, col]))
        
    result = np.stack(result_columns, axis=1)
    return result
        
    

def dot_product(A,B):
    if A.shape[0] != B.shape[0]:
        raise Exception(f'cannot multiply matrices with shapes {A.shape} and {B.shape}')
    result = 0
    for i in range(A.shape[0]):
        result +=  A[i] *B[i]
    return result

def mul2(A, B):
    """
    Mnożenie macierzy jako złożenie mnożenia wierszy przez kolumny
    """
    validate_shapes(A,B)
    C = np.zeros((A.shape[0],B.shape[1]))
    for a_row in range(A.shape[0]):
        for b_col in range(B.shape[1]):
            C[a_row][b_col] = dot_product(A[a_row,:], B[:,b_col])
    return C
print(mul2(A,B))
        

[[ -30.  -36.  -42.]
 [ -66.  -81.  -96.]
 [-102. -126. -150.]]


In [21]:
def mul3(A,B):
    validate_shapes(A,B)
    for a_col in range(A.shape[1])
        

SyntaxError: invalid syntax (<ipython-input-21-cfd772467740>, line 1)