In [1]:
import numpy as np

In [2]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
])

In [19]:
def validate_shapes(A, B):
    if A.shape[1] != B.shape[0]:
        raise Exception(f'cannot multiply matrices with shapes {A.shape} and {B.shape}')

        
def multiply_matrix_by_vector(M, V):
    """
    Mnozenie macierzy przez wektor
    """
    validate_shapes(M, V)
    M_height, M_width = M.shape
    result = np.zeros(M_height)
    
    for row in range(M_height):
        for col in range(M_width):
            result[row] += M[row, col] * V[col]
            
    return result


def mul1(A, B):
    """
    Mnozenie macierzy jako zlozenie mnozenia macierzy przez wiele wektorow.
    """
    validate_shapes(A, B)
    
    A_height, A_width = A.shape
    B_height, B_width = B.shape
    
    result_columns = []
        
    for col in range(B_width):
        result_columns.append(multiply_matrix_by_vector(A, B[:, col]))
        
    result = np.stack(result_columns, axis=1)
    return result
        
    

In [20]:
print(A @ B)
print(mul1(A, B))

[[ -30  -36  -42]
 [ -66  -81  -96]
 [-102 -126 -150]]
[[ -30.  -36.  -42.]
 [ -66.  -81.  -96.]
 [-102. -126. -150.]]


In [9]:
M @ V

array([-14, -32, -50])

In [25]:
xd = np.array([1, 2, 3]).reshape(-1, 1)
xd

array([[1],
       [2],
       [3]])